### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by michal-bootcamp** [lucluba/Step1#1]
- [x] plik `Gruntfile.js` z wielkiej litery
- [x] w gruntfile masz tez literowke tutaj `src: ['**/*.{pgn,jpg,gif}'],`
- [x] jak odpale grunta i potem otworze plik html to widze nieostylowana strone
- [x] wpis w `.gitignore` powinien wygladac tak: `node_modules/` (bez pierwszego slasha)
- [x] po kazdorazowym odpaleniu grunta dochodza coraz to nowe zagniezdzone foldery obrazkow - sprobuj to naprawic

**Comment by lucluba** [comment]
Ok jeśli chodzi o komentarze to wszystko udało się zrobić, zagnieżdżanie jak zobaczysz nie chciało pójśc poprzez zastąpienie **/*. poprzez */*. ,  ale poszło przez ./*.

**Comment by lucluba** [comment]
tutaj cos mi zmienił miało być ".. poprzez * / *. " czyli pojedyncza gwiazdka zamiast dwóch

**Comment by lucluba** [comment]
BrowserSync zrobiony i nawet działa :) dodałem też tam index.html ale właśnie widzę, że tego nie ma w watch'u to już nie zmieniałem, bo ogólny sens łapię.
Pozdrawiam

**Comment by michal-bootcamp** [comment]
super :) to teraz mam taka prosbe: 
utworz nowy branch, dokonaj w tym nowym branchu takiej zmiany, zeby wszystkie obrazki, ktore sa na stronie byly ladowane z lokalnego folderu, a nie z pexels (oczywiscie obrazki po optymalizacji imagemin). Obrazki, z placehold.it niech zostana jak sa. Nastepnie wypushuj nowy branch na githuba i wystaw na githubie pull request tego nowego brancha do mastera.

**Comment by lucluba** [comment]
Myślę, że wszystko udało mi się zrobić :)
